### ISSUE TITLE
Bad result, can it be improved?

### ISSUE THREAD

**Issue by seltix5** [gschoppe/PHP-Smart-Crop#6]
Hello,
I found a bad result with the image above for a crop of 80x60px.
Can the code be inproved or nothing can be done its just how it works...?

![image](https://user-images.githubusercontent.com/11258096/40192243-b84df114-59fb-11e8-8252-b082b30daffe.png)

![image](https://user-images.githubusercontent.com/11258096/40192254-bee3cb3e-59fb-11e8-9d3a-1d30517c3399.png)

**Comment by gschoppe** [comment]
if you look at the definition of the `find_focus()` function, the second parameter is `$weight`. that determines the weighting between color methods and entropy methods of determining center. The image you have here is just about a perfect storm for confusing smart crop, since the entropy is very high in the fine detail of the woman's hair, and is also strongly different in color from the background.

If you are using this on a photoset of mostly tightly focused images like this one, you could try modifying the weight to favor entropy more strongly than color. I never was very happy with the default weight, or the limitations of how I weighted the two against each other. There may be some tweaking you can do there to improve your results.

In general though, the more extreme the difference in proportion, and the tighter the crop of the focus area on the original image, the more likely a mis-crop is to occur.  And with a static algorithm trying to determine as complex a thing as artistic intent, there will always be the chance of error.

**Comment by seltix5** [comment]
hello,
After testing different values for the weight i finally get a better result with 0.3 or lower :
![image](https://user-images.githubusercontent.com/11258096/40273297-9c9eab5a-5bb5-11e8-9ab9-a82bda1ce33b.png)
Thanks for the help!
