### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by robsonsobral** [gschoppe/PHP-Smart-Crop#8]
Hi!

Please, what's the license of your code? Do you consider adding one? 

Thank you!

**Comment by gschoppe** [comment]
Sorry for the delayed response. It's been a while since I wrote this code, and I wanted to go back and verify that I didn't lift anything from sources or libraries that had their own encumbrances. Thankfully, after looking through all my records, everything comes back clean, so I've put the code under an MIT license
